inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  NewCops: disable
  Exclude:
    - db/schema.rb
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'bin/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
